export default {
  getCompaniesFromSuperAdminPageEndpoint: (page, sort) => `company/${page}/${sort}/`,
  singleCompany: (id) => `company/${id}/`,
  registerEndpoint: 'login',
  storageTokenKeyName: 'access_token',
  registerCompany: 'company',
  getusers: (page, sort) => `getadmins/${page}/${sort}/`,
  downloadUser: 'report/admin/',
  singleUser: (id) => `user/admin/${id}`,
  registerUser: "signup_admin/",
  getCustomers: 'customer/admin/3/all',
  singleCustomer: (id) => `customer/admin/${id}`,
  registerCustomer: 'customer/admin/3/register',
  getMarketers: 'customer/admin/2/all',
  singleMarketer: (id) => `customer/admin/${id}`,
  registerMarketer: 'customer/admin/2/register',
  getRepresentatives: 'customer/admin/1/all',
  singleRepresentatives: (id) => `customer/admin/${id}`,
  registerRepresentatives: 'customer/admin/1/register',
  createOrder: 'ordering/admin/register',
  getAdminOrders: "ordering/admin/all",
  singleHub: (id) => `hub/${id}/`,
  singleLogestic:(id) => `logistic/${id}/`,
  registerHub: 'hub',
  getHubsFromAdmin: (page, sort) => `hubs/${page}/${sort}/`,
  getLogestics: (page, sort) => `logistics/${page}/${sort}/`,
  myHub: 'hub/',
  getDrivers: 'user/admin/all?type=2',
  registerDriver: 'user/admin/courier/register',
  pricingPerKilometer: "pricing/per_kilometer",
  pricinPerSizeOfCar: (size) => `pricing/size_of_car/${size}`,
  pricingOtherOptions: "pricing/other_options",
  getPricingSizeOfCar: "pricing/size_of_car",
  singleOrder: (id) => `ordering/admin/${id}`,
  getOrder: (id) => `ordering/${id}`,
  logout: "logout/",
  loginHistory: (page, sort) => `login_report/${page}/${sort}/`,
  operationHistory: (page, sort) => `user_log/${page}/${sort}/`,
  validatePhoneByToken: 'verify_phone/',
  resetPassword: "change_password/",
  getAllCompanies: "company/all",
  getAllHubs: "hub/all",
  forgotPassword: "auth/user/forget_password",
  calculatePrice: "ordering/pricing",
  getBackups: (page, sort) => `backup/${page}/${sort}/`,
  getBackupNow: "backup/now",
  connection_to_finance: "connect_to_finance/",
  customer_percent: "pricing/customer_percent",
  singleFinancialOrder: (id) => `pricing/customer_percent/${id}`,
  createFinancialPrice: "pricing/customer_percent",
  downloadBackupById: (id) => `backup/${id}`,
  uploadBackup: 'backup/apply',
  applyBackupById: (id) => `backup/apply/${id}`,
  roles: 'user/roles',
  downloadPdf: (id) => `ordering/pdf/${id}`,
  packaging: "pricing/packaging",
  packagingById: (id) => `pricing/packaging/${id}`,
  hubReport: "report/hub/",
  logReport: "report/login_report/",
  operationReport: "report/user_log/",
  expireChange: (id, type) => type ? `company/expire/${id}/${type}/` : `company/expire/${id}/`,
  logisticReport:"report/logistic/",
  registerLogistic:"logistic"

}
